dist: trusty

language: node_js

jobs:
  include:
  - stage: "Linter"
    name: "ESLint"
    env: JOB_TYPE=linter
  - stage: "Tests"
    name: "Acceptance Tests"
    env: JOB_TYPE=acceptance_tests
  - allow_failures:
    - env: JOB_TYPE=linter

node_js:
- "8"

if: type = pull_request

env:
  global:
    - BBB_SERVER_URL=http://localhost/bigbluebutton/api

script:
  - travis_wait bash ./build_script.sh $JOB_TYPE

after_script:
  - docker stop $docker
  - docker rm $docker
  - docker rmi b2
