dist: trusty

language: node_js

matrix:
  include:
  - name: "Linter"
    env: JOB_TYPE=linter
  - name: "Tests"
    env: JOB_TYPE=tests

node_js:
- "8"

if: type = pull_request

env:
  global:
    - BBB_SERVER_URL=http://localhost/bigbluebutton/api

script:
  - travis_wait bash ./build_script.sh $JOB_TYPE

after_script:
  - docker stop $docker
  - docker rm $docker
  - docker rmi b2
